# Generated by Django 2.2.1 on 2020-05-24 15:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='count_words',
            new_name='words_count',
        ),
        migrations.RenameField(
            model_name='freq',
            old_name='count',
            new_name='count_words',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='w',
            new_name='text',
        ),
    ]
